version: '3.8'

services:
  postgres_delrey:
    image: postgres:15-alpine
    container_name: db_delrey
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: delreydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_delrey:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin_delrey:
    image: dpage/pgadmin4
    container_name: pgadmin_delrey
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@delrey.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres_delrey
    restart: unless-stopped

volumes:
  pgdata_delrey: